//! What differs between the parts this firmware runs on.
//!
//! Everything else in the crate is written against these, so adding a part is
//! adding a block here rather than editing the drivers. The selectors are the
//! `cfg` flags `esp-idf-sys` emits from the build's own sdkconfig — `esp32c3`,
//! `esp32s3` and so on — so they cannot disagree with what is actually being
//! compiled for.
//!
//! # Why raw addresses rather than the HAL
//!
//! The wire engine drives GPSPI2's registers directly because SWCLK is
//! generated by the peripheral, which is both far faster than a software loop
//! and immune to scheduler jitter. That buys ~300 KiB/s of bulk read, and it is
//! the reason these constants exist at all: an `esp-idf-hal` SPI driver would
//! be portable for free and give most of that back.
//!
//! # Adding a part
//!
//! Three numbers and a pin ceiling, taken from that part's technical reference
//! manual: the GPIO block's base, GPSPI2's base, and the highest GPIO the
//! package actually brings out. If the part has no dedicated-GPIO peripheral,
//! see [`HAS_DEDICATED_GPIO`] — the bit-bang fallback depends on it.

/// Base of the GPIO peripheral's register block.
pub const GPIO_BASE: u32 = bases().0;
/// Base of the SPI2 / GPSPI2 register block that clocks the wire.
pub const SPI2_BASE: u32 = bases().1;
/// Highest GPIO number this part exposes. A pin map is rejected at compile
/// time above this, because a firmware built for the wrong part drives pads
/// that do not exist and leaves the ones that do unclaimed.
pub const MAX_GPIO: i32 = bases().2;

/// GPIO ranges the part will not let a probe have, and why.
///
/// Driving one of these does not produce a signal, it produces a brick: the
/// SPI flash the firmware is executing from, or the USB pair it is being
/// talked to over. Checked against the pin map by a host test.
pub const RESERVED: &[(i32, i32, &str)] = reserved();

const fn reserved() -> &'static [(i32, i32, &'static str)] {
    #[cfg(any(esp32c3, not(target_os = "espidf")))]
    {
        &[
            (12, 17, "the SPI flash this firmware executes from"),
            (18, 19, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32c6)]
    {
        &[
            (24, 30, "the SPI flash this firmware executes from"),
            (12, 13, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32h2)]
    {
        &[
            (15, 21, "the SPI flash this firmware executes from"),
            (26, 27, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32s3)]
    {
        &[
            (26, 32, "the SPI flash this firmware executes from"),
            (19, 20, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32s2)]
    {
        &[
            (26, 32, "the SPI flash this firmware executes from"),
            (19, 20, "the USB pair the probe is reached over"),
        ]
    }
    #[cfg(esp32)]
    {
        // No USB peripheral at all — the original ESP32 is reached over a UART
        // bridge, so only the flash pins are off limits. GPIO34..=39 are
        // input-only, which the pin map cannot express as a range and a port
        // to this part has to handle separately.
        &[(6, 11, "the SPI flash this firmware executes from")]
    }
}

/// Whether the part has the CPU's dedicated-GPIO peripheral.
///
/// The hardware engine does not need it — GPSPI2 shifts through the GPIO
/// matrix either way — but the bit-bang fallback and the pad-level diagnostics
/// drive single levels through it. The original ESP32 predates it; everything
/// from the S2 onward has it.
pub const HAS_DEDICATED_GPIO: bool = !cfg!(esp32);

/// `(GPIO_BASE, SPI2_BASE, MAX_GPIO)` for the part being compiled for.
///
/// One function rather than three `cfg` cascades so a new part cannot be added
/// to some of them and forgotten in the others — the arms are exhaustive
/// together or the build fails on the `compile_error!` below.
const fn bases() -> (u32, u32, i32) {
    #[cfg(esp32c3)]
    {
        // ESP32-C3 TRM: GPIO 0x6000_4000, GPSPI2 0x6002_4000. GPIO0..=21,
        // with 12..=17 the SPI flash and 18/19 the USB serial/JTAG pair.
        (0x6000_4000, 0x6002_4000, 21)
    }
    #[cfg(esp32c6)]
    {
        // ESP32-C6 TRM: the peripheral map moved wholesale from the C3's.
        (0x6009_1000, 0x6008_3000, 30)
    }
    #[cfg(esp32h2)]
    {
        (0x6009_1000, 0x6008_3000, 27)
    }
    #[cfg(esp32s3)]
    {
        // S3 and S2 keep the C3's 0x600x_xxxx arrangement for these two blocks,
        // which is why they are the cheapest parts to add after the C3 — the
        // toolchain changes, the driver largely does not.
        (0x6000_4000, 0x6002_4000, 48)
    }
    #[cfg(esp32s2)]
    {
        (0x6000_4000, 0x6002_4000, 46)
    }
    #[cfg(esp32)]
    {
        // The original ESP32 sits in the older 0x3FF4_xxxx map, and its SPI2 is
        // "HSPI". It also has no dedicated-GPIO peripheral; see
        // `HAS_DEDICATED_GPIO`.
        (0x3FF4_4000, 0x3FF6_4000, 39)
    }
    // A host build compiles none of the arms above. It never touches a
    // register, but the constants still have to exist for the hardware-neutral
    // tests to link — so it gets the C3's numbers and the shape is exercised
    // without claiming anything about silicon.
    #[cfg(not(target_os = "espidf"))]
    {
        (0x6000_4000, 0x6002_4000, 21)
    }

    // Building *for* a part with no map here is a different matter: it would
    // otherwise produce a firmware that writes into empty address space, which
    // fails as a board that does nothing rather than as a build that stops.
    #[cfg(all(
        target_os = "espidf",
        not(any(esp32, esp32s2, esp32s3, esp32c3, esp32c6, esp32h2))
    ))]
    {
        compile_error!(
            "esprobe-firmware has no register map for this part. Add its GPIO base, \
             GPSPI2 base and GPIO ceiling to `chip::bases`, from its technical \
             reference manual."
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Host builds compile none of the `cfg(esp32*)` arms, so these guard the
    /// shape of the contract rather than any one part's numbers. The numbers
    /// themselves are only checked by a build for that part — and, in the end,
    /// by a board answering `esprobe pin-map`.
    #[test]
    fn the_pin_ceiling_is_a_real_gpio_number() {
        assert!(
            MAX_GPIO > 0,
            "a part with no usable GPIO cannot host a probe"
        );
        assert!(
            MAX_GPIO < 64,
            "GPIO numbering does not go this high on any ESP"
        );
    }

    #[test]
    fn the_register_blocks_are_distinct() {
        // Same base for both would mean one driver is writing into the other's
        // registers, which is the kind of transposition a fresh port makes.
        assert_ne!(GPIO_BASE, SPI2_BASE);
        assert_ne!(GPIO_BASE, 0);
        assert_ne!(SPI2_BASE, 0);
    }
}
