//! What differs between the parts this firmware runs on.
//!
//! Everything else in the crate is written against these, so adding a part is
//! adding a block here rather than editing the drivers. The selectors are the
//! `cfg` flags `esp-idf-sys` emits from the build's own sdkconfig — `esp32c3`,
//! `esp32s3` and so on — so they cannot disagree with what is actually being
//! compiled for.
//!
//! # Why raw addresses rather than the HAL
//!
//! The wire engine drives GPSPI2's registers directly because SWCLK is
//! generated by the peripheral, which is both far faster than a software loop
//! and immune to scheduler jitter. That buys ~300 KiB/s of bulk read, and it is
//! the reason these constants exist at all: an `esp-idf-hal` SPI driver would
//! be portable for free and give most of that back.
//!
//! # Adding a part
//!
//! Three numbers, and take them from ESP-IDF rather than from a datasheet or
//! from memory — `components/soc/<chip>/register/soc/reg_base.h` for
//! `DR_REG_GPIO_BASE` and `DR_REG_SPI2_BASE`, and `soc_caps.h` for
//! `SOC_GPIO_PIN_COUNT`, which is one more than the ceiling here.
//!
//! Three of the six were wrong when first written from documentation: both of
//! the C6's and H2's SPI bases, and both of the S2's, which was assumed to
//! share the S3's map on the strength of the name. None of that is visible
//! without either the headers or the silicon. If the part has no dedicated-GPIO peripheral,
//! see [`HAS_DEDICATED_GPIO`] — the bit-bang fallback depends on it.

/// Base of the GPIO peripheral's register block.
pub const GPIO_BASE: u32 = bases().0;
/// Base of the SPI2 / GPSPI2 register block that clocks the wire.
pub const SPI2_BASE: u32 = bases().1;
/// Highest GPIO number this part exposes. A pin map is rejected at compile
/// time above this, because a firmware built for the wrong part drives pads
/// that do not exist and leaves the ones that do unclaimed.
pub const MAX_GPIO: i32 = bases().2;

/// GPIO ranges the part will not let a probe have, and why.
///
/// Driving one of these does not produce a signal, it produces a brick: the
/// SPI flash the firmware is executing from, or the USB pair it is being
/// talked to over. Checked against the pin map by a host test.
///
/// The flash pads come from ESP-IDF's `SPI_*_GPIO_NUM`, not from a datasheet
/// reading — the C6's are 24..=26 and 28..=30, with 27 free between them,
/// which no plausible guess produces.
pub const RESERVED: &[(i32, i32, &str)] = reserved();

const fn reserved() -> &'static [(i32, i32, &'static str)] {
    #[cfg(any(esp32c3, not(target_os = "espidf")))]
    {
        &[
            (12, 17, "the SPI flash this firmware executes from"),
            (18, 19, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32c6)]
    {
        &[
            (24, 26, "the SPI flash this firmware executes from"),
            (28, 30, "the SPI flash this firmware executes from"),
            (12, 13, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32h2)]
    {
        &[
            (15, 20, "the SPI flash this firmware executes from"),
            (26, 27, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32s3)]
    {
        &[
            (27, 32, "the SPI flash this firmware executes from"),
            (19, 20, "the USB serial/JTAG pair the probe is reached over"),
        ]
    }
    #[cfg(esp32s2)]
    {
        &[
            (27, 32, "the SPI flash this firmware executes from"),
            (19, 20, "the USB pair the probe is reached over"),
        ]
    }
    #[cfg(esp32)]
    {
        // No USB peripheral — this part is reached over UART0, so that pair is
        // as unavailable as the flash. GPIO34..=39 are additionally input-only.
        &[
            (6, 11, "the SPI flash this firmware executes from"),
            (1, 1, "UART0 TX, the link the probe is reached over"),
            (3, 3, "UART0 RX, the link the probe is reached over"),
            (34, 39, "an input-only pad, which cannot drive a signal"),
        ]
    }
}

/// Default pin map for this part: SWDIO, SWCLK, RESET, UART_TX, UART_RX.
///
/// Not a preference — a set of constraints. A default must avoid the flash
/// pins, the pins the host link occupies, and above all the *strapping* pins,
/// which are sampled at reset: a target holding one of those at the wrong
/// level stops the probe booting at all, and the symptom is a board that
/// silently drops into ROM download mode rather than an error.
///
/// That is not hypothetical. The C3 default puts SWCLK on GPIO2, which is a
/// strapping pin, and a target holding it low costs an afternoon. It is kept
/// there because it is what the deployed boards are wired to; a fresh board
/// should override it. The original ESP32 has more strapping pins and a UART
/// host link occupying GPIO1/GPIO3, so its default avoids all of them.
pub const DEFAULT_PINS: [i32; 5] = default_pins();

const fn default_pins() -> [i32; 5] {
    #[cfg(any(esp32c3, esp32c6, esp32h2, not(target_os = "espidf")))]
    {
        // GPIO2 is a strapping pin; see above.
        [1, 2, 21, 3, 4]
    }
    #[cfg(esp32)]
    {
        // SWDIO GPIO21, SWCLK GPIO4, reset GPIO23, then the target UART.
        //
        // Avoids GPIO0/2/5/12/15 (strapping), GPIO6..=11 (flash) and
        // GPIO1/GPIO3 (UART0, which is the host link on this part). GPIO4 in
        // particular is *not* strapped, which is the whole point: a target
        // holding the clock line at reset is what stops this part entering
        // download mode, and GPIO2 — the C3's default — does exactly that.
        [21, 4, 23, 17, 16]
    }
    #[cfg(any(esp32s2, esp32s3))]
    {
        // Avoids GPIO0/45/46 (strapping), the flash bank, and GPIO19/20 (USB).
        [4, 5, 6, 17, 18]
    }
}

/// Whether the part is reached by USB Serial/JTAG rather than a UART bridge.
///
/// The original ESP32 has no USB peripheral at all, so its host link is UART0
/// and the console cannot share it.
pub const HAS_USB_SERIAL_JTAG: bool = !cfg!(esp32);

/// GPIO-matrix signal indices for the SPI peripheral that clocks the wire.
///
/// The peripheral is "GPSPI2" on the newer parts and "HSPI" on the original
/// ESP32, and `esp-idf-sys` names its signals accordingly — so these cannot be
/// one `use` shared by every part. Clock, data-out and data-in, in that order.
///
/// Data-out and data-in are both routed to the SWDIO pad: SWD is half duplex
/// on one wire, and the peripheral drives and samples the same pad.
#[cfg(target_os = "espidf")]
pub mod signals {
    #[cfg(any(esp32c3, esp32c6, esp32h2, esp32s2, esp32s3))]
    pub use esp_idf_svc::sys::{
        FSPICLK_OUT_IDX as SPI_CLK_OUT, FSPID_OUT_IDX as SPI_D_OUT, FSPIQ_IN_IDX as SPI_Q_IN,
    };
    #[cfg(esp32)]
    pub use esp_idf_svc::sys::{
        HSPICLK_OUT_IDX as SPI_CLK_OUT, HSPID_OUT_IDX as SPI_D_OUT, HSPIQ_IN_IDX as SPI_Q_IN,
    };

    // The peripheral-module handle that gates the SPI block's clock. Named
    // for the block: "SPI2" on the newer parts, "HSPI" on the original ESP32.
    #[cfg(esp32)]
    pub use esp_idf_svc::sys::periph_module_t_PERIPH_HSPI_MODULE as SPI_MODULE;
    #[cfg(any(esp32c3, esp32c6, esp32h2, esp32s2, esp32s3))]
    pub use esp_idf_svc::sys::periph_module_t_PERIPH_SPI2_MODULE as SPI_MODULE;

    /// Dedicated-GPIO input channels, where the part has them. The original
    /// ESP32 does not, and its pad layer samples the GPIO input register
    /// instead — see `crate::pads`.
    #[cfg(any(esp32c3, esp32c6, esp32h2))]
    pub use esp_idf_svc::sys::{
        CPU_GPIO_IN0_IDX as DEDICATED_IN0, CPU_GPIO_IN1_IDX as DEDICATED_IN1,
    };
}

/// Whether the part has the CPU's dedicated-GPIO peripheral.
///
/// The hardware engine does not need it — GPSPI2 shifts through the GPIO
/// matrix either way — but the bit-bang fallback and the pad-level diagnostics
/// drive single levels through it. The original ESP32 predates it; everything
/// from the S2 onward has it.
pub const HAS_DEDICATED_GPIO: bool = !cfg!(esp32);

/// `(GPIO_BASE, SPI2_BASE, MAX_GPIO)` for the part being compiled for.
///
/// One function rather than three `cfg` cascades so a new part cannot be added
/// to some of them and forgotten in the others — the arms are exhaustive
/// together or the build fails on the `compile_error!` below.
const fn bases() -> (u32, u32, i32) {
    #[cfg(esp32c3)]
    {
        // ESP32-C3 TRM: GPIO 0x6000_4000, GPSPI2 0x6002_4000. GPIO0..=21,
        // with 12..=17 the SPI flash and 18/19 the USB serial/JTAG pair.
        (0x6000_4000, 0x6002_4000, 21)
    }
    #[cfg(esp32c6)]
    {
        // The peripheral map moved wholesale from the C3's.
        (0x6009_1000, 0x6008_1000, 30)
    }
    #[cfg(esp32h2)]
    {
        (0x6009_1000, 0x6008_1000, 27)
    }
    #[cfg(esp32s3)]
    {
        // The S3 does keep the C3's arrangement for these two blocks, which
        // makes it the cheapest part to add after the C3: the toolchain
        // changes, these do not. The S2 does *not* — see below.
        (0x6000_4000, 0x6002_4000, 48)
    }
    #[cfg(esp32s2)]
    {
        // The S2 sits in the older 0x3F4x map with the original ESP32, not
        // with its S3 sibling. Grouping it with the S3 by name is wrong and
        // was, until these were checked against ESP-IDF's own `reg_base.h`.
        (0x3F40_4000, 0x3F42_4000, 46)
    }
    #[cfg(esp32)]
    {
        // The original ESP32 sits in the older 0x3FF4_xxxx map, and its SPI2 is
        // "HSPI". It also has no dedicated-GPIO peripheral; see
        // `HAS_DEDICATED_GPIO`.
        (0x3FF4_4000, 0x3FF6_4000, 39)
    }
    // A host build compiles none of the arms above. It never touches a
    // register, but the constants still have to exist for the hardware-neutral
    // tests to link — so it gets the C3's numbers and the shape is exercised
    // without claiming anything about silicon.
    #[cfg(not(target_os = "espidf"))]
    {
        (0x6000_4000, 0x6002_4000, 21)
    }

    // Building *for* a part with no map here is a different matter: it would
    // otherwise produce a firmware that writes into empty address space, which
    // fails as a board that does nothing rather than as a build that stops.
    #[cfg(all(
        target_os = "espidf",
        not(any(esp32, esp32s2, esp32s3, esp32c3, esp32c6, esp32h2))
    ))]
    {
        compile_error!(
            "esprobe-firmware has no register map for this part. Add its GPIO base, \
             GPSPI2 base and GPIO ceiling to `chip::bases`, from its technical \
             reference manual."
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Host builds compile none of the `cfg(esp32*)` arms, so these guard the
    /// shape of the contract rather than any one part's numbers. The numbers
    /// themselves are only checked by a build for that part — and, in the end,
    /// by a board answering `esprobe pin-map`.
    #[test]
    fn the_pin_ceiling_is_a_real_gpio_number() {
        assert!(
            MAX_GPIO > 0,
            "a part with no usable GPIO cannot host a probe"
        );
        assert!(
            MAX_GPIO < 64,
            "GPIO numbering does not go this high on any ESP"
        );
    }

    #[test]
    fn the_register_blocks_are_distinct() {
        // Same base for both would mean one driver is writing into the other's
        // registers, which is the kind of transposition a fresh port makes.
        assert_ne!(GPIO_BASE, SPI2_BASE);
        assert_ne!(GPIO_BASE, 0);
        assert_ne!(SPI2_BASE, 0);
    }
}
